storage:
  dbPath: /data/db

net:
  port: 27017
  bindIp: 0.0.0.0

replication:
  replSetName: rs0

setParameter:
  mongotHost: twin-mongot:27028
  searchIndexManagementHostAndPort: twin-mongot:27028
  skipAuthenticationToSearchIndexManagementServer: true
  useGrpcForSearch: true
